kind: Deployment
apiVersion: apps/v1
metadata: 
   name: deploymentpod
spec:
  replicas: 2
  selector:
    matchLabels:
      dog: terror

  template:
    metadata:
      labels:
        dog: terror

    spec:
      containers:
        - name: c1
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hello Hari; sleep 5; done" ]
