kind: Pod
apiVersion: v1
metadata:
  name: testpods
spec:
  containers:
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hellow sai; sleep 5 ; done"]


    - name: c02
      image: nginx
      ports:
        - containerPort: 80

